### ISSUE TITLE
Search doesn't work on cell data

### ISSUE THREAD

**Issue by cbizzle14** [DxCx/plugin.video.9anime#112]
Kodi 17.3 
WiFi log - paste.ubuntu.com/25340632/
Cell data log - paste.ubuntu.com/25340654/
On cell data use to not be able to find reliable sources for any shows in any of the folders (latest, recent sub, etc) but that is working now. So search is the only thing not working now.

**Comment by DxCx** [comment]
Hey @cbizzle14 unfortunately, the logs doesn't indicate anything that we can learn from.
i want to make sure i under the issue,
in menu you have "Search", when you are using it, do you get no results on cell data?
or the issue is after you are selection episode and the plugin is looking for resources?
or both?
since "Search" doesn't work refers to Search menu item results. not to video fetching as you mention inside..

**Comment by cbizzle14** [comment]
It brings up no results. A blank page. No matter what show I search for

**Comment by hoppler** [comment]
On Android 7.1.1 with Kodi 17.3 of the playstore the plugin and its search work on wlan and cell data. so my guess is, its your operatingsystem or your kodi whose the culprit.

**Comment by cbizzle14** [comment]
I don't think it's my OS because I have a different device with the same problem. So it probably is just kodi. It's just weird because it was working like a week before the problems started occurring

**Comment by hoppler** [comment]
you could always try to wipe kodi and reinstall it. with "wipe" i mean, go into appinfo of kodi and "force stop" it, afterwards go to "storage" in the same appinfo menu and "clear cache" and "clear data". then uninstall it and install it again. attention: youll loose all your kodi settings and everything like it was never installed on the device

**Comment by hoppler** [comment]
@DxCx on your next feature add run. how about extend all exception messages and extend the logging for better debug? for example check the http statuscode on return and log it. generate message for the user to see on known errors like 503 for 9anime is down, so we wont get those: "cant find sources" issues which are resolved 10 minutes later automatically. with better error logging we could maybe see, why he is not getting results in celldata

**Comment by cbizzle14** [comment]
Cleared cache and data. Uninstalled and reinstalled kodi. Now 17.4 and it still doesn't work

**Comment by DxCx** [comment]
@ratchetchan do you see the same exact problem? (Search is working only on wifi?)
@cbizzle14 - if you don't use "search" button to get to the anime, are you able to play the episode?
@hoppler - yeah we will probably need to add more debuging info to catch this...

**Comment by cbizzle14** [comment]
If I manage to find the show I'm looking for in the folders, it does work. Just tried it and currently watching an episode. Search still doesn't work

**Comment by DxCx** [comment]
alright @cbizzle14 thanks, @ratchetchan is that the same issue for you?

**Comment by DxCx** [comment]
hey @cbizzle14 
can you go to settings => system settings => Logging and enable debug log.
then paste both logs on wifi & cell?

**Comment by cbizzle14** [comment]
Search is working on cell now but here is logs
Cell Paste.ubuntu.com/25441822
WiFi Paste.ubuntu.com/25441736

**Comment by DxCx** [comment]
couldn't see anything suspicious in the logs
ok so @cbizzle14 now everything is working properly?

**Comment by cbizzle14** [comment]
Checked both devices and search is working on both
