### ISSUE TITLE
Unable to Update

### ISSUE THREAD

**Issue by FireWolf74** [DxCx/plugin.video.9anime#253]
Hey whats the deal????  I am sure I installed it from Github but zero updates.
Some help here I can't watch any anime.

![screenshot from 2018-06-17 16-33-21](https://user-images.githubusercontent.com/33334258/41511785-d02c2c20-724b-11e8-8040-5923901753a5.png)
![screenshot from 2018-06-17 16-32-19](https://user-images.githubusercontent.com/33334258/41511786-d041708a-724b-11e8-8cad-a826bb8ae706.png)

**Comment by DxCx** [comment]
did you try right click on repo and then "Check for updates"?
i always check updates on my other device and i did got latest (0.0.37)

**Comment by IceFireDude** [comment]
like to confirm I have the 9anime kodi repository and checked for updates but still on version 0.0.36

**Comment by JustAguyWhoLikesAnime** [comment]
like to confirm I have the 9anime kodi repository and checked for updates but still on version 0.0.36

**Comment by Blackreaper17** [comment]
I’m having same issues only seeing update to 0.0.36

**Comment by roworit** [comment]
Just download the zip file directly from the site and update manually. It worked for me.

**Comment by Blackreaper17** [comment]
I’m on a firestick

**Comment by roworit** [comment]
I'm not familiar with those but they're android based right?
Well this might be a roundabout way of doing it but, download the file on your pc, pass it on to your Google drive, then download it on the firestick. This should work as a fast fix.

**Comment by JustAguyWhoLikesAnime** [comment]
@Blackreaper17 you can still do it by getting a app called file commander

**Comment by Blackreaper17** [comment]
Ok so I’m not sure if the update went live but I pressed left on the remote and did a manual update checker and the file 0.0.37 showed up and updated. App is working now on firestick. Thank you

**Comment by JustAguyWhoLikesAnime** [comment]
weird has not showed up for me yet maybe it just takes time

**Comment by Blackreaper17** [comment]
Under the add-ons available update tab I pressed left on the firestick remote and selected check for more updates. This is without running a skin on Kodi 
![61211939-9e56-4238-ac31-ba1699de2979](https://user-images.githubusercontent.com/40344003/41512885-b997cac6-7257-11e8-83fe-2e03febc43f6.jpeg)

**Comment by Blackreaper17** [comment]
I just did the same thing on a different firestick and it worked as well

**Comment by epicshot01** [comment]
Here what I did, Add-ons>Add-on browser>’left button’>Check for updates. I’m using 2018 amazon fire stick

**Comment by FireWolf74** [comment]
DxCx,
Yes I verified eight ways from Sunday that according to what I have the lastest is 0.0.36.

FYI this is not Firestick or and other Android based system it is a Linux 64 bit GNOME 3.28 System.  Flavor of Linux is Fedora 28 with the latest up to date Kodi (17.6) and I did ensure that the repo I got from github was up to date as well.

**Comment by DxCx** [comment]
For all those who do not see the update,
Thats the cacheing system of kodi fooling you around..
Its abit annoying i know but there is nothing much to do but to restart kodi and try again..

**Comment by Alexjuh1** [comment]
I can't even get any update past 0.0.3 because the zip on the main page is just that

**Comment by FireWolf74** [comment]
DxCx,
Sorry to bust your bubble but it is not a cache issue.  It is a repo issue. For me at lest

**Comment by JustAguyWhoLikesAnime** [comment]
@FireWolf74 agreed it has never worked for me

**Comment by colbyanon** [comment]
I get installation failed on trying to reinstall from 9 anime repo

**Comment by jeremyjpj0916** [comment]
Currently still shows .37 only available from the repo for some reason. Hope this gets resolved its one of my favorite Kodi apps!

**Comment by jeremyjpj0916** [comment]
Okay did manage to update to .38 but still fails same error.

**Comment by andystyle09** [comment]
Good evening I would like to chime in as well I was able to update to version .38.  But I’m still getting error stating “couldn’t find eligible sources”  on all links.  Any help would be much appreciated thank you

**Comment by DxCx** [comment]
well looks like 9anime website updated something again after the fix was released..
i dont have time till evening to take a look at this unfortunately..

**Comment by jeremyjpj0916** [comment]
The battle rages on. Is what they change something that can be programatically parsed and handled? Like your app checks their site and adapts to their changes. Always interesting to try and beat sites or force them to do major overhauls to combat people 😂.

**Comment by JustAguyWhoLikesAnime** [comment]
@jeremyjpj0916  I wish I knew how you guys manage to update it as I keep having to do it manually lol

**Comment by colbyanon** [comment]
I'm on .39 update and still getting unable to find eleigible sources just letting you all know incase that helps any

**Comment by jeremyjpj0916** [comment]
I upgraded to .39 as well and still same bug. And the way I do it is by following the firestick readme guide. Dl the zip using downloader and then install from zip will setup the 9 anime repo so you can get updates automatically in future.

**Comment by d1arkstar** [comment]
ok guys if your using kodibae repository it looks like its not being update  or I should say hosted anymore the webiste I was getting it from give a 404

**Comment by DxCx** [comment]
was this issue resolved now that kodi had enough time to clear his caching?

**Comment by DxCx** [comment]
probably...
